# Generated by Django 4.2 on 2023-05-24 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Заголовки")),
                (
                    "cover_area",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="cover_area/",
                        verbose_name="Обложка",
                    ),
                ),
                (
                    "min_capacity",
                    models.PositiveSmallIntegerField(
                        verbose_name="Минимальная вместимость"
                    ),
                ),
                (
                    "max_capacity",
                    models.PositiveSmallIntegerField(
                        verbose_name="Максимальная вместимость"
                    ),
                ),
                (
                    "color_hall",
                    models.CharField(
                        choices=[
                            ("white", "Белый"),
                            ("pink", "Розовый"),
                            ("red", "Красный"),
                            ("orange", "Оранжевый"),
                            ("yellow", "Желтый"),
                            ("green", "Зеленый"),
                            ("lblue", "Голубой"),
                            ("blue", "Синий"),
                            ("purple", "Фиолетовый"),
                            ("beige", "Бежевый"),
                        ],
                        max_length=6,
                        verbose_name="Цвет зала",
                    ),
                ),
                (
                    "separate_entrance",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Отдельный вход",
                    ),
                ),
                (
                    "sale",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Скидка или подарок",
                    ),
                ),
                (
                    "min_price_banquet",
                    models.PositiveSmallIntegerField(
                        verbose_name="Минимальная цена банкета"
                    ),
                ),
                (
                    "min_price_rent",
                    models.PositiveSmallIntegerField(
                        verbose_name="Минимальная цена аренды"
                    ),
                ),
                (
                    "deposit",
                    models.PositiveSmallIntegerField(verbose_name="Предоплата"),
                ),
                (
                    "scheme_of_payment",
                    models.CharField(
                        choices=[
                            ("bah", "Аренда зала + банкет"),
                            ("ban", "Только банкет"),
                            ("hall", "Только зал"),
                        ],
                        max_length=4,
                        verbose_name="Схема оплаты",
                    ),
                ),
                (
                    "detail_location",
                    models.CharField(
                        max_length=1000, verbose_name="Дополнительная информация"
                    ),
                ),
                (
                    "reserved_days",
                    models.DateField(null=True, verbose_name="Зарезервированная дата"),
                ),
            ],
            options={
                "verbose_name": "Место",
                "verbose_name_plural": "Места",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("wed", "Свадьба"),
                            ("birth", "День рождения"),
                            ("nyr", "Новый год"),
                            ("buf", "Фуршет"),
                            ("bach", "Мальчишник"),
                            ("bclt", "Девичник"),
                            ("cmp", "Корпоратив"),
                            ("fest", "Праздничный банкет"),
                            ("grd", "Выпускной"),
                        ],
                        max_length=6,
                        verbose_name="Подходит для",
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие",
                "verbose_name_plural": "События",
            },
        ),
        migrations.CreateModel(
            name="Features",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_feature",
                    models.CharField(
                        choices=[
                            ("guestr", "Номер для гостей"),
                            ("room", "Номер для новобрачных"),
                            ("proj", "Есть проектор"),
                            ("tv", "ТВ-экраны"),
                            ("dance", "Есть танцпол"),
                            ("scen", "Есть сцена"),
                            ("brid", "Есть комната невесты"),
                            ("dress", "Есть примерочная"),
                            ("pan", "Панорамный вид"),
                            ("phot", "Фотозона"),
                        ],
                        max_length=6,
                        verbose_name="Особенности деталей площадки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Деталь площадки",
                "verbose_name_plural": "Детали площадки",
            },
        ),
        migrations.CreateModel(
            name="Kitchen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kitchen",
                    models.CharField(
                        choices=[
                            ("eur", "Европейская"),
                            ("asia", "Азиатская"),
                            ("rus", "Русская"),
                            ("cau", "Кавказская"),
                            ("ita", "Итальянская"),
                            ("jap", "Японская"),
                            ("kor", "Корейская"),
                            ("other", "Другая"),
                        ],
                        max_length=5,
                        verbose_name="Кухни",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кухня",
                "verbose_name_plural": "Кухни",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("sea", "Около моря"),
                            ("river", "Около реки"),
                            ("outc", "За городом"),
                            ("inc", "В городе"),
                            ("icc", "В центре города"),
                            ("forest", "В лесу"),
                            ("lake", "Около озера"),
                            ("imt", "В горах"),
                        ],
                        max_length=6,
                        verbose_name="Локация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вид локации",
                "verbose_name_plural": "Виды локаций",
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cover_place",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="cover_place/",
                        verbose_name="Обложка",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, verbose_name="Название площадки"),
                ),
                ("city", models.CharField(max_length=20, verbose_name="Город")),
                (
                    "metro",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Станция метро",
                    ),
                ),
                ("address", models.CharField(max_length=300, verbose_name="Адресс")),
                ("longitude", models.FloatField(verbose_name="Долгота")),
                ("width", models.FloatField(verbose_name="Широта")),
                (
                    "id_yandex",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Id на яндекс картах",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Начало работы")),
                ("finish_time", models.TimeField(verbose_name="Конец работы")),
                (
                    "fireworks",
                    models.BooleanField(verbose_name="Можно запустить фейерверки?"),
                ),
                (
                    "children_kitchen",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Детское меню",
                    ),
                ),
                (
                    "alco",
                    models.BooleanField(
                        blank=True,
                        default=True,
                        null=True,
                        verbose_name="Можно принести свой алкоголь?",
                    ),
                ),
                (
                    "payment_of_alco",
                    models.PositiveSmallIntegerField(
                        verbose_name="Плата за пронос вашего алкоголя"
                    ),
                ),
                (
                    "lease_extension",
                    models.BooleanField(verbose_name="Продление аренды"),
                ),
                (
                    "lease_extension_price",
                    models.PositiveSmallIntegerField(
                        verbose_name="Cтоимость продления аренды"
                    ),
                ),
                (
                    "average_check",
                    models.PositiveSmallIntegerField(verbose_name="Средний чек"),
                ),
                ("description", models.TextField(verbose_name="Описание площадки")),
                (
                    "parking",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Вместимость парковки"
                    ),
                ),
                (
                    "max_serving",
                    models.PositiveSmallIntegerField(
                        verbose_name="Сколько обслуживает один официант"
                    ),
                ),
                (
                    "territory_desc",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Описание территории",
                    ),
                ),
                (
                    "event",
                    models.ManyToManyField(
                        to="catalogapp.event", verbose_name="Подходит для"
                    ),
                ),
                (
                    "kitchen",
                    models.ManyToManyField(
                        to="catalogapp.kitchen", verbose_name="Кухни"
                    ),
                ),
                (
                    "location",
                    models.ManyToManyField(
                        to="catalogapp.location", verbose_name="Локации"
                    ),
                ),
                (
                    "type_feature",
                    models.ManyToManyField(
                        to="catalogapp.features",
                        verbose_name="Особенности деталей площадки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Площадка",
                "verbose_name_plural": "Площадки",
            },
        ),
        migrations.CreateModel(
            name="TypeArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_area",
                    models.CharField(
                        choices=[
                            ("bqh", "Банкетный зал"),
                            ("tent", "Шатер"),
                            ("vrnd", "Веранда"),
                            ("ycc", "Яхт-клуб"),
                            ("mts", "Теплоход"),
                            ("loft", "Лофт"),
                            ("mnr", "Усадьба"),
                            ("rsrn", "Ресторан"),
                            ("cafe", "Кафе"),
                            ("rct", "База отдыха"),
                            ("ctg", "Коттедж"),
                            ("htl", "Отель"),
                            ("cst", "Замок"),
                            ("cntc", "Загородный клуб"),
                            ("cntn", "Столовая"),
                        ],
                        max_length=5,
                        verbose_name="Тип площадки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вид места",
                "verbose_name_plural": "Виды мест",
            },
        ),
        migrations.CreateModel(
            name="TypePlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_place",
                    models.CharField(
                        choices=[
                            ("site", "Площадки"),
                            ("zags", "Дворец бракосочетания"),
                            ("present", "Ведущие"),
                            ("photo", "Фотографы"),
                            ("design", " Оформление и декор"),
                            ("org", "Организаторы"),
                            ("dj", "Диджеи"),
                            ("invit", "Приглашения"),
                            ("video", "Видеографы"),
                            ("flor", " Флористика и букеты"),
                            ("style", "Стилисты"),
                            ("visage", "Визажисты"),
                            ("music", "Музыкальные группы"),
                            ("anim", "Детские аниматоры"),
                            ("chor", "Хореографы"),
                            ("show", "Шоу-программа"),
                            ("las", "Свет и звук"),
                            ("bah", "Красота и здоровье"),
                            ("cad", "Торты и десерты"),
                            ("weddr", "Свадебные платья"),
                            ("mensuit", "Мужские костюмы"),
                            ("wedri", "Обручальные кольца"),
                            ("brsmdr", "Платья подружек невесты"),
                            ("transp", "Транспорт"),
                            ("barmen", "Бармены"),
                            ("firew", "Фейерверки"),
                        ],
                        max_length=7,
                        verbose_name="Тип площадки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип площадки",
                "verbose_name_plural": "Типы площадок",
            },
        ),
        migrations.CreateModel(
            name="TypeTerritory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_territory",
                    models.CharField(
                        choices=[
                            ("park", "Своя парковка"),
                            ("welc", "Welcome-зона"),
                            ("fire", "Место под фаер-шоу"),
                            ("firew", "Можно фейерверк"),
                            ("hotel", "Отель рядом"),
                            ("kids", "Детская игровая зона"),
                            ("phot", "Фотозона"),
                            ("reg", "С выездной регистрацией"),
                            ("pan", "Панорамный вид"),
                            ("guesth", "Отель для гостей"),
                        ],
                        max_length=6,
                        verbose_name="территория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Территория",
                "verbose_name_plural": "Территории",
            },
        ),
        migrations.CreateModel(
            name="WelcomeZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "welcome_desc",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Описание welcome зоны",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="welcome_zones",
                        to="catalogapp.place",
                        verbose_name="К какой площадке относится",
                    ),
                ),
            ],
            options={
                "verbose_name": "welcome - зона",
                "verbose_name_plural": "welcome - зоны",
            },
        ),
        migrations.AddField(
            model_name="place",
            name="type_place",
            field=models.ManyToManyField(
                to="catalogapp.typeplace", verbose_name="Тип площадки"
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="type_territory",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="catalogapp.typeterritory",
                verbose_name="Территории",
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Id владельца",
            ),
        ),
        migrations.CreateModel(
            name="OutsiteRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "outreg_price",
                    models.PositiveSmallIntegerField(
                        verbose_name="Стоимост выездной регистрации"
                    ),
                ),
                (
                    "outreg_conditions",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Условия выездной регистрации",
                    ),
                ),
                (
                    "outreg_include",
                    models.CharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        verbose_name="Входит в выездную регистрацию",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outsites_reg",
                        to="catalogapp.place",
                        verbose_name="К какой площадке относится",
                    ),
                ),
            ],
            options={
                "verbose_name": "Выездная регистрация",
                "verbose_name_plural": "Выездные регистрации",
            },
        ),
        migrations.CreateModel(
            name="ImageWelcomeZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="image_welcome/", verbose_name="Фото  welcome зоны"
                    ),
                ),
                (
                    "welcome_zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images_welcome",
                        to="catalogapp.welcomezone",
                        verbose_name="Welcome-зона",
                    ),
                ),
            ],
            options={
                "verbose_name": "Картинка welcome зоны",
                "verbose_name_plural": "Картинки welcome зоны",
            },
        ),
        migrations.CreateModel(
            name="ImageWedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="image_wedding/", verbose_name="Фото прошедших свадеб"
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images_wedding",
                        to="catalogapp.place",
                        verbose_name="Место проведения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Картинка прошедшeй свадьбы",
                "verbose_name_plural": "Картинки прошедших свадеб",
            },
        ),
        migrations.CreateModel(
            name="ImageTerritory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="image_territories/", verbose_name="Фото территории"
                    ),
                ),
                (
                    "territory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_territory",
                        to="catalogapp.place",
                        verbose_name="Площадка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Картинка территории",
                "verbose_name_plural": "Картинки территории",
            },
        ),
        migrations.CreateModel(
            name="ImagePlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="image_place/", verbose_name="Фото площадки"
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images_place",
                        to="catalogapp.place",
                        verbose_name="Площадка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Картинка площадки",
                "verbose_name_plural": "Картинки площадок",
            },
        ),
        migrations.CreateModel(
            name="ImageOutsiteReg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="image_territories/", verbose_name="Фото территории"
                    ),
                ),
                (
                    "outsite_reg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images_out_reg",
                        to="catalogapp.outsiteregistration",
                        verbose_name="Выездная регистрация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Картинка выездной регистрации",
                "verbose_name_plural": "Картинки выездной регистрации",
            },
        ),
        migrations.CreateModel(
            name="ImageArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="image_area/", verbose_name="Фото места"
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images_area",
                        to="catalogapp.area",
                        verbose_name="Место",
                    ),
                ),
            ],
            options={
                "verbose_name": "Картинка места",
                "verbose_name_plural": "Картинки мест",
            },
        ),
        migrations.AddField(
            model_name="area",
            name="place",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="areas",
                to="catalogapp.place",
                verbose_name="Относится к какой площадке",
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="type_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="catalogapp.typearea",
                verbose_name="Тип площадки",
            ),
        ),
    ]
